<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ironyx.Kernel.Execution" Version="1.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ironyx.ServiceIndex.Api\Ironyx.ServiceIndex.Api.csproj" />
    <ProjectReference Include="..\Ironyx.ServiceIndex.Infrastructure\Ironyx.ServiceIndex.Infrastructure.csproj" />
  </ItemGroup>

</Project>
